### ISSUE TITLE
finalize PC composition

### ISSUE THREAD

**Issue by e-maud** [cohure/CHR-2021#4]
@ManuelBurghardt @jorisvanzundert and all

- [ ] proposing and asking for proposition of candidates to extend the initial list: first draft in this file: https://docs.google.com/spreadsheets/d/1rxBLOtii68mC21BkM2_1iQ2EO0T-5eRTNyeEdL38I_I/edit#gid=0
- [ ] validation by all OC members
- [ ] drafting PC member invitation email. See first attempt here: https://docs.google.com/document/d/1Rr1ooGmfkfpz07k0saWI918cnQSD1TdJaH6rWN1k6p4/edit#heading=h.ig2b5fe615ae
- [ ] sending invitation via easychair
- [ ] sending reminders via easychair

**Comment by melvinwevers** [comment]
For last year's edition, we tried to keep a diverse and interdisciplinary reviewer pool, which was quite challenging. 
It might be useful if we would indicate the reviewer's expertise in the spreadsheet. This would make it easier to build up a diverse group of reviewers.

**Comment by jorisvanzundert** [comment]
Can we assume that current PC members know about task 1 (adding potential reviewers)? Or should this be mailed out once again?
